/* VIZKOR V2: syncs the existing EPSReg learning banks into one reviewer. */
(()=>{
 const BASE='../', status={state:'loading',sources:{},added:0}; window.VIZKOR_REPO_STATUS=status;
 const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
 const split=s=>{s=clean(s);const p=s.lastIndexOf(' / ');return p>0?[s.slice(0,p).trim(),s.slice(p+3).trim()]:[s,'']};
 const dedupe=a=>{const m=new Map();for(const v of a){if(!v?.ko||!v?.en)continue;const k=clean(v.ko)+'|'+clean(v.en);if(!m.has(k))m.set(k,v)}return [...m.values()]};
 async function text(path){try{const r=await fetch(BASE+path,{cache:'no-store'});if(!r.ok)throw Error(r.status);const t=await r.text();status.sources[path]={ok:true,bytes:t.length};return t}catch(e){status.sources[path]={ok:false,error:String(e)};return ''}}
 function balanced(t,marker){let p=t.indexOf(marker),s=t.indexOf('[',p);if(p<0||s<0)return '';let d=0,q=null,esc=false;for(let i=s;i<t.length;i++){let c=t[i];if(q){if(esc){esc=false;continue}if(c==='\\'){esc=true;continue}if(c===q)q=null;continue}if(c==='"'||c==="'"){q=c;continue}if(c==='[')d++;else if(c===']'&&--d===0)return t.slice(s,i+1)}return ''}
 function noun(t){const out=[];const re=/\{\s*"ko"\s*:\s*"((?:\\.|[^"\\])*)"\s*,\s*"en"\s*:\s*"((?:\\.|[^"\\])*)"\s*,\s*"tl"\s*:\s*"((?:\\.|[^"\\])*)"\s*,\s*"page"\s*:\s*(\d+)\s*,\s*"book"\s*:\s*(\d+)\s*\}/g;let m;while((m=re.exec(t)))out.push({ko:m[1],en:m[2],tl:m[3],page:+m[4],book:'B'+m[5],pos:'Noun',source:'noun.js'});return out}
 function master(t,pos,source){const raw=balanced(t,'const WORDS_MASTER');if(!raw)return [];let a=[];try{a=JSON.parse(raw)}catch{return []}return a.map(o=>{let [en,tl]=split(o.en);return {ko:clean(o.ko),en,tl,page:+o.page||0,book:'B'+(+o.book||1),pos,source,present:o.present||null,past:o.past||null,future:o.future||null}})}
 function loose(t,pos,source){const out=[];const re=/\{\s*(?:level\s*:\s*(["'])(.*?)\1\s*,\s*)?ko\s*:\s*(["'])(.*?)\3\s*,\s*en\s*:\s*(["'])(.*?)\5\s*,\s*tl\s*:\s*(["'])(.*?)\7\s*\}/g;let m;while((m=re.exec(t)))out.push({ko:clean(m[4]),en:clean(m[6]),tl:clean(m[8]),book:'B1',pos,source,level:m[2]||''});return out}
 function jsonish(t,pos,source){const out=[];const re=/\{\s*"ko"\s*:\s*"((?:\\.|[^"\\])*)"\s*,\s*"en"\s*:\s*"((?:\\.|[^"\\])*)"(?:\s*,\s*"tl"\s*:\s*"((?:\\.|[^"\\])*)")?/g;let m;while((m=re.exec(t)))out.push({ko:m[1],en:m[2],tl:m[3]||'',book:'B1',pos,source});return out}
 async function sync(){const files=['noun.js','verb.js','adjective.js','adverb.html','greetings.html','sentence.html','keyword.js'];const [n,v,a,ad,g,s,k]=await Promise.all(files.map(text));let vocab=dedupe([...noun(n),...master(v,'Verb','verb.js'),...master(a,'Adjective','adjective.js'),...loose(ad,'Adverb','adverb.html'),...loose(g,'Expression','greetings.html'),...jsonish(k,'EPS Keyword','keyword.js')]);let sentences=dedupe(loose(s,'Sentence','sentence.html'));window.VIZKOR_DATA={vocab,sentences};status.added=vocab.length;status.state='ready';status.lastSync=new Date().toISOString();window.dispatchEvent(new CustomEvent('vizkor:data-ready',{detail:status}))}
 sync().catch(e=>{status.state='error';status.error=String(e);window.dispatchEvent(new CustomEvent('vizkor:data-ready',{detail:status}))});
})();