(() => {
  'use strict';
  const TTS_RATE = 0.85;
  const CACHE_PREFIX = 'vizkor_curated_noun_v1_';
  const ids=['search','category','book','review','limit','page','selectedPrompt','copySelected','clearCache','exportMapping','reload','status','loadError','cards','empty','sTotal','sCat','sReview','sCurated','sB1','sB2'];
  const els=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
  let nouns=[],filtered=[],voices=[];

  const ambiguousSenses={
    '배':['pear','boat','ship','stomach'],'눈':['eye','snow'],'말':['horse','speech','word'],'밤':['night','chestnut'],'굴':['cave','oyster'],'병':['bottle','illness','disease'],'장':['chapter','market','sheet','piece'],'금':['gold','Friday'],'일':['work','job','day','one'],'의사':['doctor','physician','opinion','intention'],'차':['car','tea','difference'],'사과':['apple','apology'],'기사':['driver','engineer','article','knight'],'약':['medicine','approximately'],'방':['room','method','direction'],'표':['ticket','table','chart','mark'],'풀':['grass','glue'],'김':['steam','seaweed']
  };
  const categoryHints={
    'Animals':'single animal full body realistic','Food & Drinks':'food item realistic isolated','Places':'place building exterior realistic','Home & Household':'household object realistic','Occupations & Professions':'person profession realistic','Transportation':'vehicle full view realistic','Clothing & Accessories':'clothing item product photo','School & Office Supplies':'school office item product photo','Nature & Weather':'nature weather realistic','Body & Health':'educational medical image','Technology & Modern Life':'device technology product photo','People & Relationships':'person relationship realistic','Materials':'material sample realistic','Education & Study':'school study object realistic','Health & Medicine':'medical object or professional realistic','Work & Career':'workplace worker object realistic'
  };

  function clean(v=''){return String(v??'').replace(/\s+/g,' ').trim()}
  function lower(v=''){return clean(v).toLowerCase()}
  function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function slug(v=''){return clean(v).replace(/[^0-9A-Za-z가-힣]+/g,'_').replace(/^_+|_+$/g,'').slice(0,90)}
  function flatten(data){const out=[];for(const [categoryKey,group] of Object.entries(data||{})){if(categoryKey==='all'||!group||!Array.isArray(group.data))continue;const category=clean(group.name?.en||categoryKey);for(const row of group.data){if(!row||!clean(row.ko))continue;out.push({...row,ko:clean(row.ko),en:clean(row.en),tl:clean(row.tl),category,categoryKey})}}return out}
  function parseNounScript(text){const fn=new Function(`${text}\n;return typeof CATEGORIZED_NOUNS !== 'undefined' ? CATEGORIZED_NOUNS : null;`);const data=fn();if(!data)throw new Error('CATEGORIZED_NOUNS was not found in noun.js');return flatten(data)}
  function senseFor(item){const en=lower(item.en),choices=ambiguousSenses[item.ko]||[];const hit=choices.find(s=>en.includes(s));if(hit)return hit;return en.split(/[\/,;(]/)[0].trim()||en}
  function reviewFlags(item){const flags=[],en=lower(item.en);if(ambiguousSenses[item.ko])flags.push({type:'warn',label:'Ambiguous Korean word'});if(item.category==='Occupations & Professions'&&/opinion|intention/.test(en))flags.push({type:'bad',label:'Likely category mismatch'});if(item.category==='People & Relationships'&&/^(yard|window|pizza)$/.test(en))flags.push({type:'bad',label:'Likely category mismatch'});if(item.ko==='교실'&&!en.includes('classroom'))flags.push({type:'warn',label:'Meaning should be checked'});if(/moumtain|chopstiks/.test(en))flags.push({type:'bad',label:'English spelling issue'});if(!item.en)flags.push({type:'bad',label:'Missing English meaning'});return flags}
  function searchQuery(item){const sense=senseFor(item);const hint=categoryHints[item.category]||'clear educational image realistic';return `${item.ko} ${item.en} ${sense} ${hint}`.replace(/\s+/g,' ').trim()}
  function googleUrl(item){return `https://www.google.com/search?tbm=isch&q=${encodeURIComponent(searchQuery(item))}`}
  function commonsUrl(item){return `https://commons.wikimedia.org/w/index.php?search=${encodeURIComponent(item.en||senseFor(item))}&title=Special:MediaSearch&type=image`}
  function key(item){return `${CACHE_PREFIX}${slug(item.ko)}__${slug(item.en)}__b${item.book||0}p${item.page||0}`}
  function getCurated(item){try{const raw=localStorage.getItem(key(item));return raw?JSON.parse(raw):null}catch{return null}}
  function setCurated(item,obj){try{localStorage.setItem(key(item),JSON.stringify(obj));return true}catch(e){alert('Could not save image in browser storage. Try a smaller image or use an image URL.');return false}}
  function removeCurated(item){try{localStorage.removeItem(key(item))}catch{}}
  function allCurated(){const rows=[];try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k?.startsWith(CACHE_PREFIX))continue;try{rows.push({cacheKey:k,...JSON.parse(localStorage.getItem(k))})}catch{}}}catch{}return rows}
  function curatedCount(){return nouns.filter(n=>!!getCurated(n)).length}
  function placeholder(item){const icons={'Animals':'🐾','Food & Drinks':'🍎','Places':'🏢','Transportation':'🚌','Clothing & Accessories':'👕','Home & Household':'🏠','Occupations & Professions':'🧑‍🔧','Body & Health':'🩺','Nature & Weather':'🌤️','School & Office Supplies':'✏️','Technology & Modern Life':'💻'};return `<div class="image-placeholder"><div class="emoji">${icons[item.category]||'🖼️'}</div><b>No curated image yet</b><span>${esc(item.ko)} · ${esc(item.en)}</span></div>`}
  function refreshVoices(){try{voices=speechSynthesis.getVoices()||[]}catch{voices=[]}}
  function speak(text){if(!('speechSynthesis'in window))return;try{speechSynthesis.cancel()}catch{}const u=new SpeechSynthesisUtterance(clean(text).replace(/[()]/g,''));u.lang='ko-KR';u.rate=TTS_RATE;u.pitch=1;u.volume=1;const voice=voices.find(v=>lower(v.lang)==='ko-kr')||voices.find(v=>lower(v.lang).startsWith('ko'));if(voice)u.voice=voice;speechSynthesis.speak(u)}

  function askUrl(item){const current=getCurated(item);const entered=prompt(`Paste an approved image URL for:\n${item.ko} — ${item.en}`,current?.type==='url'?current.src:'https://');if(!entered||entered==='https://')return;const obj={ko:item.ko,en:item.en,tl:item.tl||'',category:item.category,book:item.book||0,page:item.page||0,sense:senseFor(item),type:'url',src:entered,sourceUrl:entered,query:searchQuery(item),savedAt:new Date().toISOString()};if(setCurated(item,obj)){updateStats();applyFilters(false)}}
  function uploadImage(item){const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>{const file=input.files?.[0];if(!file)return;const img=new Image(),reader=new FileReader();reader.onload=()=>{img.onload=()=>{const max=640,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);let dataUrl;try{dataUrl=canvas.toDataURL('image/webp',.82)}catch{dataUrl=reader.result}const obj={ko:item.ko,en:item.en,tl:item.tl||'',category:item.category,book:item.book||0,page:item.page||0,sense:senseFor(item),type:'upload',src:dataUrl,fileName:file.name,query:searchQuery(item),savedAt:new Date().toISOString()};if(setCurated(item,obj)){updateStats();applyFilters(false)}};img.src=reader.result};reader.readAsDataURL(file)};input.click()}
  function exportMapping(){const data=allCurated().map(({cacheKey,...x})=>x);const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),count:data.length,images:data},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='VIZKOR_Noun_Curated_Images.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

  function applyFilters(resetPage=false){const q=lower(els.search.value),category=els.category.value,book=els.book.value,mode=els.review.value;if(resetPage)els.page.value='1';filtered=nouns.filter(item=>{if(q&&!lower(`${item.ko} ${item.en} ${item.tl} ${item.category}`).includes(q))return false;if(category&&item.category!==category)return false;if(book&&String(item.book)!==book)return false;const needs=reviewFlags(item).some(f=>f.type==='warn'||f.type==='bad'),cur=!!getCurated(item);if(mode==='review'&&!needs)return false;if(mode==='clear'&&needs)return false;if(mode==='curated'&&!cur)return false;if(mode==='missing'&&cur)return false;return true});const per=Number(els.limit.value||12),pages=Math.max(1,Math.ceil(filtered.length/per)),current=Math.min(Number(els.page.value||1),pages);els.page.innerHTML=Array.from({length:pages},(_,i)=>`<option value="${i+1}"${i+1===current?' selected':''}>${i+1}</option>`).join('');render()}
  function render(){const per=Number(els.limit.value||12),page=Number(els.page.value||1),start=(page-1)*per,rows=filtered.slice(start,start+per);els.cards.innerHTML='';els.empty.style.display=rows.length?'none':'block';els.status.textContent=`${filtered.length.toLocaleString()} matched · page ${page} of ${Math.max(1,Math.ceil(filtered.length/per))}`;for(const item of rows){const flags=reviewFlags(item),cur=getCurated(item),query=searchQuery(item),card=document.createElement('article');card.className='card';card.innerHTML=`<div class="imagebox"><div class="image-content" style="width:100%;height:100%;display:flex;align-items:center;justify-content:center">${cur?`<img src="${esc(cur.src)}" alt="${esc(item.en)}">`:placeholder(item)}</div>${cur?'<div class="approved">CURATED ✓</div>':''}</div><div class="cardbody"><div class="ko-row"><div class="ko">${esc(item.ko)}</div><button class="speak" title="Speak slowly">🔊</button></div><div class="en">${esc(item.en||'—')}</div><div class="tl">${esc(item.tl||'')}</div><div class="meta">${esc(item.category)}${item.book?` · Book ${item.book}`:''}${item.page?` · Page ${item.page}`:''}</div><div class="tags">${flags.map(f=>`<span class="tag ${f.type}">${esc(f.label)}</span>`).join('')||'<span class="tag good">Clear noun</span>'}<span class="tag info">Sense: ${esc(senseFor(item))}</span>${cur?'<span class="tag good">Image saved</span>':''}</div><div class="query"><b>Search query:</b> ${esc(query)}</div><div class="cardfoot"><a class="btn primary" href="${googleUrl(item)}" target="_blank" rel="noopener">Google Images</a><a class="btn" href="${commonsUrl(item)}" target="_blank" rel="noopener">Wikimedia</a><button class="btn url">Paste Image URL</button><button class="btn upload">Upload Image</button><button class="btn show">Show Search Query</button>${cur?'<button class="btn danger remove">Remove Image</button>':'<button class="btn" disabled>No image saved</button>'}</div></div>`;card.querySelector('.speak').addEventListener('click',()=>speak(item.ko));card.querySelector('.url').addEventListener('click',()=>askUrl(item));card.querySelector('.upload').addEventListener('click',()=>uploadImage(item));card.querySelector('.show').addEventListener('click',()=>{els.selectedPrompt.value=query;els.selectedPrompt.scrollIntoView({behavior:'smooth',block:'center'})});const remove=card.querySelector('.remove');if(remove)remove.addEventListener('click',()=>{removeCurated(item);updateStats();applyFilters(false)});els.cards.appendChild(card)}}
  function updateStats(){const cats=[...new Set(nouns.map(n=>n.category).filter(Boolean))].sort();els.category.innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');els.sTotal.textContent=nouns.length.toLocaleString();els.sCat.textContent=cats.length.toLocaleString();els.sReview.textContent=nouns.filter(n=>reviewFlags(n).some(f=>f.type==='warn'||f.type==='bad')).length.toLocaleString();els.sCurated.textContent=curatedCount().toLocaleString();els.sB1.textContent=nouns.filter(n=>Number(n.book)===1).length.toLocaleString();els.sB2.textContent=nouns.filter(n=>Number(n.book)===2).length.toLocaleString()}
  async function loadNouns(){els.loadError.style.display='none';els.status.textContent='Loading Version 1 noun.js…';try{const r=await fetch('../noun.js?preview='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(`noun.js HTTP ${r.status}`);nouns=parseNounScript(await r.text());if(!nouns.length)throw new Error('No noun entries were parsed.');updateStats();applyFilters(true)}catch(err){console.error(err);els.status.textContent='Could not load noun.js';els.loadError.textContent=`Preview load error: ${err.message}`;els.loadError.style.display='block'}}
  ['input','change'].forEach(evt=>{els.search.addEventListener(evt,()=>applyFilters(true));els.category.addEventListener(evt,()=>applyFilters(true));els.book.addEventListener(evt,()=>applyFilters(true));els.review.addEventListener(evt,()=>applyFilters(true));els.limit.addEventListener(evt,()=>applyFilters(true))});els.page.addEventListener('change',render);els.reload.addEventListener('click',loadNouns);els.copySelected.addEventListener('click',async()=>{if(!els.selectedPrompt.value)return;try{await navigator.clipboard.writeText(els.selectedPrompt.value);els.copySelected.textContent='Copied ✓';setTimeout(()=>els.copySelected.textContent='Copy selected query',1000)}catch{}});els.exportMapping.addEventListener('click',exportMapping);els.clearCache.addEventListener('click',()=>{if(!confirm('Clear all curated noun images saved in this browser preview?'))return;try{for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k?.startsWith(CACHE_PREFIX))localStorage.removeItem(k)}}catch{}updateStats();applyFilters(false)});if('speechSynthesis'in window){refreshVoices();speechSynthesis.addEventListener?.('voiceschanged',refreshVoices)}loadNouns();
})();
